name: Build, Test, and Publish

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
            7.0.x
  
      - name: Install tools
        run: |
          dotnet tool restore
  
      - name: Build Release
        run: dotnet build -c Release /p:ContinuousIntegrationBuild=true

      - name: Build Debug
        run: dotnet build -c Debug

      - name: Run test suite
        run: dotnet test --no-build ReportyyTests/ReportyyTests.csproj -c Release

      - name: Run test suite (Debug)
        run: dotnet test --no-build ReportyyTests/ReportyyTests.csproj -c Debug

      - name: Pack
        run: dotnet pack Reportyy.net -c Release --no-build --output nuget

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: nuget/

  publish:
    name: Publish
    if: (((github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) && startsWith(github.ref, 'refs/tags/v'))
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: nuget
        path: nuget
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Publish NuGet packages to NuGet
      run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source "nuget.org"